
import { Employee } from "../types";

export const brandingTeam: Employee[] = [
  {
    id: "7",
    name: "Indhu",
    role: "Director Design and Research",
    department: "Branding",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8.5,
      workHoursThisWeek: 42,
      lateNightCheckins: 2,
      burnoutScore: 58,
      workLifeBalance: 7.4,
    },
    leaves: {
      total: 24,
      taken: 6,
      planned: 5,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 2,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Design research", hours: 8.5 },
    ],
  },
  {
    id: "8",
    name: "Pooja",
    role: "Lead Brand Strategist",
    department: "Branding",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 45,
      workLifeBalance: 8.0,
    },
    leaves: {
      total: 22,
      taken: 5,
      planned: 4,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Brand strategy meeting", hours: 7.5 },
    ],
  },
  {
    id: "13",
    name: "Gowtham",
    role: "Junior Brand Designer",
    department: "Branding",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7,
      workHoursThisWeek: 35,
      lateNightCheckins: 0,
      burnoutScore: 35,
      workLifeBalance: 8.5,
    },
    leaves: {
      total: 20,
      taken: 3,
      planned: 2,
      sickLeaves: 1,
      sick: 1,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 0,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Brand design work", hours: 7 },
    ],
  },
  {
    id: "14",
    name: "Afreetha",
    role: "Junior Brand Designer",
    department: "Branding",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 40,
      workLifeBalance: 8.2,
    },
    leaves: {
      total: 20,
      taken: 4,
      planned: 3,
      sickLeaves: 1,
      sick: 1,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Creative design session", hours: 7.5 },
    ],
  },
  {
    id: "19",
    name: "Arjun",
    role: "Junior Brand Strategist",
    department: "Branding",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 42,
      workLifeBalance: 8.1,
    },
    leaves: {
      total: 20,
      taken: 3,
      planned: 2,
      sickLeaves: 1,
      sick: 1,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 0,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Strategy planning", hours: 7.5 },
    ],
  },
];
