
import { Employee } from "../types";

export const digitalDesignTeam: Employee[] = [
  {
    id: "1",
    name: "Harish Venkatesh",
    role: "Founder",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8.5,
      workHoursThisWeek: 42,
      lateNightCheckins: 3,
      burnoutScore: 65,
      workLifeBalance: 7.2,
    },
    leaves: {
      total: 24,
      taken: 6,
      planned: 5,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 2,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Late night check-in", hours: 2.5 },
      { date: "2024-03-14", action: "Normal work day", hours: 8 },
      { date: "2024-03-13", action: "Early checkout", hours: 6 },
    ],
  },
  {
    id: "2",
    name: "Vasantha Kumar",
    role: "Junior Digital Designer",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 38,
      lateNightCheckins: 1,
      burnoutScore: 45,
      workLifeBalance: 8.1,
    },
    leaves: {
      total: 20,
      taken: 4,
      planned: 3,
      sickLeaves: 1,
      sick: 1,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Normal work day", hours: 8 },
      { date: "2024-03-14", action: "Creative session", hours: 7.5 },
    ],
  },
  {
    id: "9",
    name: "Sandeep",
    role: "Associate Digital Designer",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8,
      workHoursThisWeek: 40,
      lateNightCheckins: 2,
      burnoutScore: 55,
      workLifeBalance: 7.5,
    },
    leaves: {
      total: 22,
      taken: 5,
      planned: 4,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Design review", hours: 8 },
    ],
  },
  {
    id: "10",
    name: "Gokul",
    role: "Junior Digital Designer",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7,
      workHoursThisWeek: 35,
      lateNightCheckins: 0,
      burnoutScore: 35,
      workLifeBalance: 8.5,
    },
    leaves: {
      total: 20,
      taken: 3,
      planned: 2,
      sickLeaves: 1,
      sick: 1,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 0,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Learning session", hours: 7 },
    ],
  },
  {
    id: "11",
    name: "Preksha",
    role: "Associate Digital Designer",
    department: "Digital Design",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8,
      workHoursThisWeek: 40,
      lateNightCheckins: 1,
      burnoutScore: 50,
      workLifeBalance: 7.8,
    },
    leaves: {
      total: 22,
      taken: 6,
      planned: 3,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 1,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Client presentation", hours: 8 },
    ],
  },
  {
    id: "12",
    name: "Shri Karthick Adhithya",
    role: "Junior Digital Designer",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 40,
      workLifeBalance: 8.2,
    },
    leaves: {
      total: 20,
      taken: 3,
      planned: 2,
      sickLeaves: 1,
      sick: 1,
      casual: 1,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Design iteration", hours: 7.5 },
    ],
  },
  {
    id: "4",
    name: "Samuel",
    role: "Lead Webflow Developer",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 9,
      workHoursThisWeek: 45,
      lateNightCheckins: 4,
      burnoutScore: 70,
      workLifeBalance: 6.5,
    },
    leaves: {
      total: 24,
      taken: 7,
      planned: 6,
      sickLeaves: 3,
      sick: 3,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 2,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Code deployment", hours: 9 },
      { date: "2024-03-14", action: "Late night debugging", hours: 10 },
    ],
  },
  {
    id: "17",
    name: "Prity",
    role: "Associate Webflow Partner",
    department: "Digital Design",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 45,
      workLifeBalance: 8.0,
    },
    leaves: {
      total: 22,
      taken: 6,
      planned: 4,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 1,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Webflow development", hours: 7.5 },
    ],
  },
  {
    id: "18",
    name: "Noothan",
    role: "Developer Intern",
    department: "Digital Design",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 6,
      workHoursThisWeek: 30,
      lateNightCheckins: 0,
      burnoutScore: 25,
      workLifeBalance: 9.0,
    },
    leaves: {
      total: 15,
      taken: 2,
      planned: 2,
      sickLeaves: 1,
      sick: 1,
      casual: 1,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 0,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Learning and development", hours: 6 },
    ],
  },
];
