
import { Employee } from "../types";

export const frontrunnerTeam: Employee[] = [
  {
    id: "15",
    name: "Thangavel",
    role: "Content Strategist",
    department: "Frontrunner",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8,
      workHoursThisWeek: 40,
      lateNightCheckins: 2,
      burnoutScore: 50,
      workLifeBalance: 7.8,
    },
    leaves: {
      total: 22,
      taken: 5,
      planned: 3,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Content strategy meeting", hours: 8 },
    ],
  },
  {
    id: "16",
    name: "Juhi",
    role: "Growth and Partnerships",
    department: "Frontrunner",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 8.5,
      workHoursThisWeek: 42.5,
      lateNightCheckins: 3,
      burnoutScore: 62,
      workLifeBalance: 7.2,
    },
    leaves: {
      total: 24,
      taken: 6,
      planned: 4,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 2,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Partnership calls", hours: 8.5 },
    ],
  },
  {
    id: "20",
    name: "Divya",
    role: "Communication Designer",
    department: "Frontrunner",
    gender: "Female",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 7.5,
      workHoursThisWeek: 37.5,
      lateNightCheckins: 1,
      burnoutScore: 45,
      workLifeBalance: 8.0,
    },
    leaves: {
      total: 22,
      taken: 5,
      planned: 3,
      sickLeaves: 2,
      sick: 2,
      casual: 2,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 1,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Design communication materials", hours: 7.5 },
    ],
  },
  {
    id: "21",
    name: "Siddharth",
    role: "Co-founder CEO of Frontrunner",
    department: "Frontrunner",
    gender: "Male",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    metrics: {
      workHoursToday: 9.5,
      workHoursThisWeek: 47.5,
      lateNightCheckins: 4,
      burnoutScore: 75,
      workLifeBalance: 6.2,
    },
    leaves: {
      total: 24,
      taken: 2,
      planned: 8,
      sickLeaves: 1,
      sick: 1,
      casual: 1,
      emergency: 0,
      bereavement: 0,
      maternity: 0,
      paternity: 0,
      menstrual: 0,
      compensatory: 0,
    },
    recentActivity: [
      { date: "2024-03-15", action: "Strategic planning", hours: 9.5 },
      { date: "2024-03-14", action: "Late night planning session", hours: 10 },
    ],
  },
];
